version: "3.9"

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - shortener
      - redirector

  shortener:
    build: ./shortener
    ports:
      - "8001:8000"

  redirector:
    build: ./redirector
    ports:
      - "8002:8000"

#   postgres:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: url_user
#       POSTGRES_PASSWORD: url_pass
#       POSTGRES_DB: urls_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data

#   redis:
#     image: redis:7
#     ports:
#       - "6379:6379"

# volumes:
#   pg_data: